ALTER TABLE meals
  ADD COLUMN IF NOT EXISTS fiber DOUBLE PRECISION;

ALTER TABLE meals
  ADD COLUMN IF NOT EXISTS sugar_alcohols DOUBLE PRECISION;

ALTER TABLE favorite_meals
  ADD COLUMN IF NOT EXISTS fiber DOUBLE PRECISION;

ALTER TABLE favorite_meals
  ADD COLUMN IF NOT EXISTS sugar_alcohols DOUBLE PRECISION;

ALTER TABLE favorite_meal_items
  ADD COLUMN IF NOT EXISTS fiber DOUBLE PRECISION;

ALTER TABLE favorite_meal_items
  ADD COLUMN IF NOT EXISTS sugar_alcohols DOUBLE PRECISION;
