export {
  BEVERAGE_TYPES,
  BEVERAGE_UNITS as WATER_UNITS,
  aggregateBeverageEntriesByDate as aggregateWaterEntriesByDate,
  buildBeverageRecordedAt as buildWaterRecordedAt,
  calculateDailyWaterTarget,
  convertBeverageToFlOz as convertWaterToFlOz,
  convertFlOzToUnit,
  formatBeverageAmount as formatWaterAmount,
  formatBeverageFromFlOz as formatWaterFromFlOz,
  formatBeverageValue as formatWaterValue,
  getBeverageUnitMeta as getWaterUnitMeta,
  getDefaultBeverageTime as getDefaultWaterTime,
  getHydrationHelperCopy,
  getPreferredBeverageUnit as getPreferredWaterUnit,
  getWaterQuickAddOptions,
  normalizeBeverageEntryInput as normalizeWaterEntryInput,
  summarizeBeverageEntries as summarizeWaterEntries,
} from './beverages.js';
